services:
  frontend:
    build:
      context: ./frontend
    image: ayan-warsame-frontend:1.0.0
    container_name: appointment-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: ayan-warsame-backend:1.0.0
    container_name: appointment-backend
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=appointments.db
    volumes:
      - ./backend/appointments.db:/app/appointments.db
