services:
  frontend:
    build:
      context: ./frontend
    image: ayan-warsame-frontend:1.0.0
    container_name: appointment-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: ayan-warsame-backend:1.0.0
    container_name: appointment-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=appointments
      - DB_USER=admin
      - DB_PASSWORD=admin2266#
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    container_name: appointment-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=appointments
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin2266#
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
