version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: appointment-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: appointment-backend
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=appointments.db
    volumes:
      - ./backend/appointments.db:/app/appointments.db
