apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.nameOverride | default .Chart.Name }}
  labels:
    app: frontend
    {{- include "ayan-warsame-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend

