{{- if .Values.serviceAccount.frontend.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.frontend.name }}
  namespace: {{ .Values.nameOverride | default .Chart.Name }}
  labels:
    {{- include "ayan-warsame-app.labels" . | nindent 4 }}
    app: frontend
{{- end }}

---
{{- if .Values.serviceAccount.backend.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.backend.name }}
  namespace: {{ .Values.nameOverride | default .Chart.Name }}
  labels:
    {{- include "ayan-warsame-app.labels" . | nindent 4 }}
    app: backend
{{- end }}

{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-role
  namespace: {{ .Values.nameOverride | default .Chart.Name }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: {{ .Values.nameOverride | default .Chart.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: [{{ .Values.database.credentials.secretName | quote }}]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-rolebinding
  namespace: {{ .Values.nameOverride | default .Chart.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.frontend.name }}
  namespace: {{ .Values.nameOverride | default .Chart.Name }}
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: {{ .Values.nameOverride | default .Chart.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.backend.name }}
  namespace: {{ .Values.nameOverride | default .Chart.Name }}
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}

