apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: ayan-warsame-prometheus
  namespace: ayan-warsame
  labels:
    release: prometheus
    app: prometheus
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  ruleSelector:
    matchLabels:
      release: prometheus
  podMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
      cpu: 200m
    limits:
      memory: 800Mi
      cpu: 500m
  retention: 7d
  alerting:
    alertmanagers:
    - namespace: ayan-warsame
      name: alertmanager
      port: web
  serviceMonitorNamespaceSelector:
    matchNames:
    - ayan-warsame
